refactors

diff --git a/test b/test
--- a/test
+++ b/test
@@ -46,6 +46,11 @@ while [ "$#" -gt 0 ]; do
   esac
 done
 
+if [[ -n "$SCRIPT" ]] && ! [[ -s "$SCRIPT" ]]; then
+  echo "Script not found: $SCRIPT"
+  exit 1
+fi
+
 while IFS= read -r -d '' FILE
 do
   FILES+=("$FILE")
